package entities;
// Generated May 29, 2017 12:16:54 AM by Hibernate Tools 4.3.1



/**
 * Degree generated by hbm2java
 */
public class Degree  implements java.io.Serializable {


     private int degreeId;
     private String degreeName;

    public Degree() {
    }

	
    public Degree(int degreeId) {
        this.degreeId = degreeId;
    }
    public Degree(int degreeId, String degreeName) {
       this.degreeId = degreeId;
       this.degreeName = degreeName;
    }
   
    public int getDegreeId() {
        return this.degreeId;
    }
    
    public void setDegreeId(int degreeId) {
        this.degreeId = degreeId;
    }
    public String getDegreeName() {
        return this.degreeName;
    }
    
    public void setDegreeName(String degreeName) {
        this.degreeName = degreeName;
    }




}


